[tool.commitizen]
name = "cz_conventional_commits"
version_files = [
  "setup.py:version",
  "pyproject.toml:version"
]
version = "0.1.2"
tag_format = "$major.$minor.$patch$prerelease"
# try bumping before push? not sure
