[tool.commitizen]
name = "cz_conventional_commits"
changelog_file = "CHANGELOG.md"
changelog_incremental = true
update_changelog_on_bump = true
version_files = [
    "pyproject.toml:version",
    "setup.py:version"
]
version = "0.3.0"
tag_format = "$major.$minor.$patch$prerelease"
