[tool.commitizen]
name = "cz_conventional_commits"
version_files = [
    "pyproject.toml:version",
    "setup.py:version"
]
version = "0.1.0"
tag_format = "$major.$minor.$patch$prerelease"
changelog_incremental = true
